# Generated by Django 3.2.9 on 2021-11-28 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20211128_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='driver_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='cars.driver', verbose_name='Водитель'),
        ),
    ]
