# Generated by Django 3.2.9 on 2021-12-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_vehicle_driver_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='driver_id',
            new_name='driver',
        ),
    ]
